#!/usr/bin/env python3
"""Write COVERAGE.md: what each bundled grid prices and which stations are on the map."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NETWORKS = ROOT / "Sources" / "TollKit" / "Resources" / "networks"


def app_key(name):
    """Same normalisation as StationName.key in TollKit (and build_tariffs.app_key)."""
    import re
    import unicodedata
    s = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode().upper()
    s = re.sub(r"(\bS)?/\s*", " SUR ", s)
    s = re.sub(r"\bCH\.", "CHATEAU ", s)
    s = s.replace("SAINTE", "STE").replace("SAINT", "ST")
    return " ".join(re.sub(r"[^A-Z0-9]+", " ", s).split())


def main():
    docs = [json.loads(p.read_text()) for p in sorted(NETWORKS.glob("*.json"))]
    lines = [
        "# Coverage",
        "",
        "Generated by `Tools/coverage.py` from the bundled data.",
        "",
        "*Located* means the route detector can find the station: by its toll booths",
        "(OpenStreetMap `barrier=toll_booth`) or, failing that, by the exit nodes of its",
        "interchange (`highway=motorway_junction`). *Virtual* entries are not places you",
        "can enter or leave (concession limits, motorway forks, the open-system marker,",
        "borders); they are priced but never detected on a route.",
        "",
        "| Grid | Valid from | Fares | Toll points | Stations | Virtual | By booth | By interchange | Not located |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    totals = [0] * 7
    missing = {}
    for d in docs:
        st = d["stations"]
        virtual = [s for s in st if s.get("virtual")]
        real = [s for s in st if not s.get("virtual")]
        booth = [s for s in real if s.get("booths")]
        junction = [s for s in real if s.get("junctions") and not s.get("booths")]
        other = [s for s in real if "lat" in s and not s.get("booths") and not s.get("junctions")]
        unlocated = [s for s in real if "lat" not in s]
        pts = d.get("points", [])
        row = [len(d["fares"]), len(pts), len(st), len(virtual), len(booth) + len(other), len(junction), len(unlocated)]
        totals = [a + b for a, b in zip(totals, row)]
        lines.append(f"| {d['name']} | {d['validFrom']} | " + " | ".join(f"{v:,}" for v in row) + " |")
        if unlocated:
            missing[d["name"]] = sorted(s["name"] for s in unlocated)
        unlocated_points = [p["name"] for p in pts if "lat" not in p]
        if unlocated_points:
            missing.setdefault(d["name"], []).extend(f"{n} (toll point)" for n in unlocated_points)
    lines.append("| **Total** | | " + " | ".join(f"**{v:,}**" for v in totals) + " |")
    real_total = totals[2] - totals[3]
    located = totals[4] + totals[5]
    # The engine merges stations with the same normalised name across grids
    # (TollDatabase), so a station unlocated in one grid can be located by another.
    merged = {}
    for d in docs:
        for s in d["stations"]:
            if s.get("virtual"):
                continue
            merged[app_key(s["name"])] = merged.get(app_key(s["name"]), False) or "lat" in s
    lines += ["", f"{located:,} of {real_total:,} real grid entries are located ({100 * located / real_total:.0f} %).",
              f"After merging entries that name the same station in several grids, "
              f"{sum(merged.values()):,} of {len(merged):,} stations are located "
              f"({100 * sum(merged.values()) / len(merged):.0f} %); "
              f"{sum('lat' in p for d in docs for p in d.get('points', []))} of {totals[1]} toll points are.", ""]
    for name in list(missing):
        missing[name] = [n for n in missing[name] if n.endswith("(toll point)") or not merged.get(app_key(n))]
        if not missing[name]:
            del missing[name]
    lines += ["## Not located", "",
              "These stations are priced exactly when named in an itinerary, but a route",
              "through them will not detect them.", ""]
    for name, stations in missing.items():
        lines.append(f"- **{name}** ({len(stations)}): " + ", ".join(stations))
    (ROOT / "COVERAGE.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines[10:10 + len(docs) + 4]))


if __name__ == "__main__":
    main()
